# Generated by Django 3.2 on 2021-05-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstapp', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image1',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image2',
            new_name='Style',
        ),
    ]
