# Generated by Django 3.1.2 on 2021-05-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstapp', '0004_auto_20210507_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Content',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Style',
            new_name='image2',
        ),
    ]
